
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'VERBS WORDSsentence : WORDS VERBS sentence\n                | sen1sen1 : WORDS sen1\n            | WORDS'
    
_lr_action_items = {'WORDS':([0,2,4,5,],[2,4,4,2,]),'$end':([1,2,3,4,6,7,],[0,-4,-2,-4,-3,-1,]),'VERBS':([2,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sentence':([0,5,],[1,7,]),'sen1':([0,2,4,5,],[3,6,6,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sentence","S'",1,None,None,None),
  ('sentence -> WORDS VERBS sentence','sentence',3,'p_sentence','sentence.py',22),
  ('sentence -> sen1','sentence',1,'p_sentence','sentence.py',23),
  ('sen1 -> WORDS sen1','sen1',2,'p_sen1','sentence.py',30),
  ('sen1 -> WORDS','sen1',1,'p_sen1','sentence.py',31),
]
